language: node_js
node_js:
- stable
branches:
  only:
  - master
install: npm install
before_script:
- git config --global user.name "Emil Hein via Travis Ci"
- git config --global user.email "emilhein1@gmail.com"
- sed -i "s/GH_TOKEN/${GH_TOKEN}/" _config.yml
script:
- hexo clean
- hexo g
- hexo d